### ISSUE TITLE
Redis healthcheck

### ISSUE THREAD

**Issue by steevehook** [docker-library/healthcheck#13]
Healthcheck command fails if redis.conf is provided. I ran this manually and I get this error:

`Could not connect to Redis at 172.17.0.2:6379: Connection refused`

My assumption is either `localhost` or `127.0.0.1` should stay, instead of fetching the host ip

Here is my Dockerfile

![image](https://user-images.githubusercontent.com/16312516/39050916-ccbe814c-44af-11e8-8b9f-e194ed264b69.png)

**Comment by steevehook** [comment]
Sorry, looks like the problem was in `redis.conf`. I needed to comment out the `bind 127.0.0.1` line to make it accessible outside

**Comment by tianon** [comment]
Nice, glad you got it figured out! :+1:
