### ISSUE TITLE
Questions about enable_materialized_views and enable_transient_replication

### ISSUE THREAD

**Issue by ghost** [docker-library/healthcheck#19]
Thanks for providing this useful container! I have a question about two cassandra configs: `enable_materialized_views` and `enable_transient_replication.` It seems the [official document](http://cassandra.apache.org/doc/latest/configuration/cassandra_config_file.html)
does not recommend to enable them in production but but they are set to be enabled in  `/etc/cassandra/cassandra.yaml`:

![image](https://user-images.githubusercontent.com/4555674/56547979-b8392100-6533-11e9-9347-aafdfaef4721.png)

Shall we disable them?
Thanks!

**Comment by tianon** [comment]
This is definitely not the appropriate place to discuss this.  This repository is examples of using the `HEALTHCHECK` command in Docker against various official images.
