### ISSUE TITLE
Are these compatible with swarm mode?

### ISSUE THREAD

**Issue by p-diogo** [docker-library/healthcheck#2]
Hello all!

Thanks for sharing this. I've tried your healtcheck method with postgres using https://hub.docker.com/r/mdillon/postgis/~/dockerfile/ as the base image and everything works as expected when in non-swarm mode. Whenever I try to the same image in swarm mode, it never stays in `running` mode. Is it incompatible? It looks like it is ready to run, but, after a while, there is a shutdown request, as seen in the logs:

```
test-swarm_db.1.w83nr7m4m3wq@test-docker-swarm-test2-manager    | LOG:  received smart shutdown request
test-swarm_db.1.w83nr7m4m3wq@test-docker-swarm-test2-manager    | LOG:  autovacuum launcher shutting down
test-swarm_db.1.w83nr7m4m3wq@test-docker-swarm-test2-manager    | LOG:  shutting down
test-swarm_db.1.w83nr7m4m3wq@test-docker-swarm-test2-manager    | LOG:  database system is shut down
test-swarm_db.1.juy14y8pi8xu@test-docker-swarm-test2-manager    | LOG:  database system was shut down at 2017-03-21 16:43:58 UTC
```

Thank you all in advance!

EDIT: Nvm, it looks like everything is ok - I just add a versioning problem....

**Comment by tianon** [comment]
I'm not sure how `HEALTHCHECK` and Swarm Mode interact -- when you run your service outside Swarm Mode, does it stay marked healthy?

**Comment by tianon** [comment]
https://github.com/docker/docker/issues/26498 does seem to imply that Swarm Mode takes `HEALTHCHECK` into account, and documents something similar to what you're seeing (a service takes too long to start up, so Swarm Mode shuts it down)

**Comment by p-diogo** [comment]
@tianon thanks a lot for the quick reply! I'm not entirely sure what went wrong, but it is now working fine... It does take a lit bit to determine whether the service is running, but it is working.
