### ISSUE TITLE
Change interval

### ISSUE THREAD

**Issue by Clara-Lu** [docker-library/healthcheck#6]
Hi!

I am using the `healthcheck/mysql`. The interval for healthcheck seems to be set to 30s by default from my observation. I am wondering is there a way to change the interval?

Thanks!!

**Comment by yosifkit** [comment]
It looks like they can be adjusted on the `docker run` (and should also work on `docker service create`):
```console
      --health-cmd string                     Command to run to check health
      --health-interval duration              Time between running the check (ns|us|ms|s|m|h) (default 0s)
      --health-retries int                    Consecutive failures needed to report unhealthy
      --health-timeout duration               Maximum time to allow one check to run (ns|us|ms|s|m|h) (default 0s)
      --no-healthcheck                        Disable any container-specified HEALTHCHECK
```

**Comment by sean9999** [comment]
Those same flags can be added directly into Dockerfile

https://docs.docker.com/engine/reference/builder/#healthcheck

**Comment by tianon** [comment]
Indeed, these values _can_ be changed directly in the `Dockerfile` itself, but since these are simply example prototypes, I think we'll stick to the defaults for now. :+1: :heart:
