### ISSUE TITLE
Healthcheck script execution permissions in alpine

### ISSUE THREAD

**Issue by REDNBLACK** [docker-library/healthcheck#7]
Healthcheck scripts didn't work (timeout and service unhealthy in docker ps) in alpine images of **rabbitmq** and **postgres**, until i added the following command in Dockerfile:
`RUN chmod +x /usr/local/bin/docker-healthcheck`

Docker CE v17.03.0-ce-mac2 (15654)

**Comment by tianon** [comment]
You need to invoke `chmod +x` on your local copy of the script if you didn't use `git clone` to download the repository before building. :+1:
