### ISSUE TITLE
More version tags

### ISSUE THREAD

**Issue by kichooo** [docker-library/healthcheck#8]
It would be nice to be able to use specific version of postgres:

for instance: 

postgres:
    image: healthcheck/postgres:9.5

**Comment by KaelBaldwin** [comment]
same for mysql

**Comment by tianon** [comment]
See my comment on https://github.com/docker-library/healthcheck/issues/11#issuecomment-428348749 (referencing https://github.com/docker-library/cassandra/pull/76#issuecomment-246054271), especiall this bit:

> ... this repository exists precisely as an _example_ for users to set up their own `HEALTHCHECK`s which are relevant to their deployments.  Many users are going to need modifications, etc, which is why I'd honestly not recommend users use these images directly, and why I'd be hesitant to do things like tag multiple versions which might encourage more users to do so.
